### ISSUE TITLE
Issue in node-sp-auth

### ISSUE THREAD

**Issue by mduiveman84** [YannickRe/vsts-sharepoint-alm#1]
You have a dependency on node-sp-auth. We recently noticed a issue where resolving the tenantid when connecting with clientid&secret fails. It looks like the issue is a typo in the url when posting to client.svc. I submitted a [issue](https://github.com/s-KaiNet/node-sp-auth/issues/48) to the author of node-sp-auth. 

Because of this issue, uploading a spfx package using clientid and secret fails.
Please be aware of this issue, and when the author fixes it, can you update you're dependancy with this lib..

**Comment by YannickRe** [comment]
I followed the issue with node-sp-auth, thank you for investigating. When running my tests, it succeeded so it must have been a recent change.
Since node-sp-auth was updated, I pushed out release 2.0.4 of the extension with the latest version of the dependencies. Should show up automatically in your VSTS/TFS.
